apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lnaura/LMV-Cluster-manifests.git'
    #repoURL: 'https://github.com/Autoever-Cloud/argocd-lmv-cluster-manifests.git'
    targetRevision: HEAD
    path: base/eck-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true