apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample # 배포할 Kibana의 이름
  namespace: efkstack
spec:
  version: 8.12.2 # Elasticsearch와 동일한 버전으로 설정
  count: 1 # Kibana 인스턴스는 1개만 생성
  elasticsearchRef:
    name: es-cluster # 연결할 Elasticsearch 클러스터의 이름
  http:
    service:
      spec:
        # ECK Operator가 생성할 서비스의 타입을 LoadBalancer로 지정
        type: LoadBalancer 
    tls:
      selfSignedCertificate:
        disabled: false
  config:
    server.publicBaseUrl: "https://192.168.201.234:55601"
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.security.authc.providers:
      anonymous.anonymous1:
        order: 0
        credentials:
          username: "anonymous_service_account"
          password: "anonymous_service_account_password"
      # 2. basic 인증은 후순위(order: 1)로 둡니다.
      basic.basic1:
        order: 1
    # 3. [핵심] 인증 제공자 선택 화면을 비활성화합니다.
    xpack.security.authc.selector.enabled: false
    xpack.security.sameSiteCookies: "None" # 'None'은 문자열로 처리
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 1Gi
            cpu: 1
        env:
        - name: KIBANA_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: kibana-encryption-key
              key: key
        readinessProbe:
          httpGet:
            path: /api/status  # 가볍고 빠른 상태 체크 전용 API
            port: 5601
            scheme: HTTPS
          initialDelaySeconds: 30 # Kibana가 시작할 시간을 충분히 줍니다.
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3